#!/bin/bash

gmessage "Are you sure you want to shutdown/logout of your computer?" -center -title "Take action" -font "Sans bold 10" -default "Cancel" -buttons "_Cancel":1,"_Log out":2 >/dev/null

case $? in
1)
echo "Cancel";;
2)
killall i3;;
esac
